version: "3.8"
services:
  pytorch:
    container_name: pytorch
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    volumes:
      - ./notebooks/:/app/
    working_dir: /app/
    command: "jupyter notebook --no-browser --ip=0.0.0.0 --NotebookApp.token=''"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
